SET DEFINE OFF;
Insert into PERSONAL.PARAMETRO_NOMINA
   (CO_PROCESO_NOM, CO_PARAMETRO_NOM, VA_PARAMETRO_NOM, TX_PARAMETRO_NOM)
 Values
   ('ENCU', '1', 805, 'ACETAMINOFEN+TRAMADOL 325 MG/37,5 MG X 10 TABLETAS');
Insert into PERSONAL.PARAMETRO_NOMINA
   (CO_PROCESO_NOM, CO_PARAMETRO_NOM, VA_PARAMETRO_NOM, TX_PARAMETRO_NOM)
 Values
   ('ENCU', '2', 380, 'ALPRAZOLAM 1 MG X 40 TABLETAS');
Insert into PERSONAL.PARAMETRO_NOMINA
   (CO_PROCESO_NOM, CO_PARAMETRO_NOM, VA_PARAMETRO_NOM, TX_PARAMETRO_NOM)
 Values
   ('ENCU', '3', 8.32, 'AMPICILINA 500 MG X 16 CAPSULAS');
Insert into PERSONAL.PARAMETRO_NOMINA
   (CO_PROCESO_NOM, CO_PARAMETRO_NOM, VA_PARAMETRO_NOM, TX_PARAMETRO_NOM)
 Values
   ('ENCU', '4', 288, 'BROMAZEPAM 6 MG X 40 TABLETAS');
Insert into PERSONAL.PARAMETRO_NOMINA
   (CO_PROCESO_NOM, CO_PARAMETRO_NOM, VA_PARAMETRO_NOM, TX_PARAMETRO_NOM)
 Values
   ('ENCU', '5', 930, 'CALOXPIRINA 81 MG X 30 TABLETAS');
Insert into PERSONAL.PARAMETRO_NOMINA
   (CO_PROCESO_NOM, CO_PARAMETRO_NOM, VA_PARAMETRO_NOM, TX_PARAMETRO_NOM)
 Values
   ('ENCU', '6', 8500, 'CARVEDILOL 25 MG X  14 TAB ');
Insert into PERSONAL.PARAMETRO_NOMINA
   (CO_PROCESO_NOM, CO_PARAMETRO_NOM, VA_PARAMETRO_NOM, TX_PARAMETRO_NOM)
 Values
   ('ENCU', '8', 1600, 'CARVEDILOL 6,25 MG X 112 BLISTER X 7 TAB');
Insert into PERSONAL.PARAMETRO_NOMINA
   (CO_PROCESO_NOM, CO_PARAMETRO_NOM, VA_PARAMETRO_NOM, TX_PARAMETRO_NOM)
 Values
   ('ENCU', '9', 3200, 'CARVEDILOL 6,25 MG X 112 BLISTER X 7 TAB');
Insert into PERSONAL.PARAMETRO_NOMINA
   (CO_PROCESO_NOM, CO_PARAMETRO_NOM, VA_PARAMETRO_NOM, TX_PARAMETRO_NOM)
 Values
   ('ENCU', '7', 4250, 'CARVEDILOL25 MG X 75 BLISTER X 7 TAB');
Insert into PERSONAL.PARAMETRO_NOMINA
   (CO_PROCESO_NOM, CO_PARAMETRO_NOM, VA_PARAMETRO_NOM, TX_PARAMETRO_NOM)
 Values
   ('ENCU', '10', 7800, 'CIPROFLOXACINA 500 MG X 14 TAB ');
Insert into PERSONAL.PARAMETRO_NOMINA
   (CO_PROCESO_NOM, CO_PARAMETRO_NOM, VA_PARAMETRO_NOM, TX_PARAMETRO_NOM)
 Values
   ('ENCU', '11', 7800, 'CIPROFLOXACINA 500 MG X 62 BLISTER X 14 TAB');
Insert into PERSONAL.PARAMETRO_NOMINA
   (CO_PROCESO_NOM, CO_PARAMETRO_NOM, VA_PARAMETRO_NOM, TX_PARAMETRO_NOM)
 Values
   ('ENCU', '13', 3000, 'DICLOFENAC POTASICO 50 MG X 85  BLISTER X 10 TAB');
Insert into PERSONAL.PARAMETRO_NOMINA
   (CO_PROCESO_NOM, CO_PARAMETRO_NOM, VA_PARAMETRO_NOM, TX_PARAMETRO_NOM)
 Values
   ('ENCU', '12', 1000, 'DICLOFENAC SODICO 50 mg x 30 TABLETAS');
Insert into PERSONAL.PARAMETRO_NOMINA
   (CO_PROCESO_NOM, CO_PARAMETRO_NOM, VA_PARAMETRO_NOM, TX_PARAMETRO_NOM)
 Values
   ('ENCU', '14', 1280, 'DIOSMINA 600 MG  X 14 TABLETAS');
Insert into PERSONAL.PARAMETRO_NOMINA
   (CO_PROCESO_NOM, CO_PARAMETRO_NOM, VA_PARAMETRO_NOM, TX_PARAMETRO_NOM)
 Values
   ('ENCU', '15', 950, 'DOL PLUS X 10 TABLETAS');
Insert into PERSONAL.PARAMETRO_NOMINA
   (CO_PROCESO_NOM, CO_PARAMETRO_NOM, VA_PARAMETRO_NOM, TX_PARAMETRO_NOM)
 Values
   ('ENCU', '16', 1600, 'DOL PLUS X 20 TABLETAS');
Insert into PERSONAL.PARAMETRO_NOMINA
   (CO_PROCESO_NOM, CO_PARAMETRO_NOM, VA_PARAMETRO_NOM, TX_PARAMETRO_NOM)
 Values
   ('ENCU', '17', 800, 'DOL X 10 TABLETAS');
Insert into PERSONAL.PARAMETRO_NOMINA
   (CO_PROCESO_NOM, CO_PARAMETRO_NOM, VA_PARAMETRO_NOM, TX_PARAMETRO_NOM)
 Values
   ('ENCU', '18', 1400, 'DOL X 20 TABLETAS');
Insert into PERSONAL.PARAMETRO_NOMINA
   (CO_PROCESO_NOM, CO_PARAMETRO_NOM, VA_PARAMETRO_NOM, TX_PARAMETRO_NOM)
 Values
   ('ENCU', '19', 500, 'DOMPERIDONA 10 MG X 15 TABLETAS');
Insert into PERSONAL.PARAMETRO_NOMINA
   (CO_PROCESO_NOM, CO_PARAMETRO_NOM, VA_PARAMETRO_NOM, TX_PARAMETRO_NOM)
 Values
   ('ENCU', '20', 1300, 'LANSOPRAZOL 30 MG X 28 CAPSULAS');
Insert into PERSONAL.PARAMETRO_NOMINA
   (CO_PROCESO_NOM, CO_PARAMETRO_NOM, VA_PARAMETRO_NOM, TX_PARAMETRO_NOM)
 Values
   ('ENCU', '21', 40.88, 'OMEPRAZOL 20 MG X 28 CAPSULAS');
Insert into PERSONAL.PARAMETRO_NOMINA
   (CO_PROCESO_NOM, CO_PARAMETRO_NOM, VA_PARAMETRO_NOM, TX_PARAMETRO_NOM)
 Values
   ('ENCU', '22', 700, 'PANTOPRAZOL 20 MG X 7 TABLETAS');
Insert into PERSONAL.PARAMETRO_NOMINA
   (CO_PROCESO_NOM, CO_PARAMETRO_NOM, VA_PARAMETRO_NOM, TX_PARAMETRO_NOM)
 Values
   ('ENCU', '23', 480, 'PINAVERIUM BROMURO 50 MG X 20 TABLETAS');
Insert into PERSONAL.PARAMETRO_NOMINA
   (CO_PROCESO_NOM, CO_PARAMETRO_NOM, VA_PARAMETRO_NOM, TX_PARAMETRO_NOM)
 Values
   ('ENCU', '24', 6000, 'SERTRALINA 50 MG X 10 TABLETAS');
Insert into PERSONAL.PARAMETRO_NOMINA
   (CO_PROCESO_NOM, CO_PARAMETRO_NOM, VA_PARAMETRO_NOM, TX_PARAMETRO_NOM)
 Values
   ('ENCU', '25', 6000, 'SERTRALINA 50 MG X 100 BLISTER X 10 TABLETAS');
Insert into PERSONAL.PARAMETRO_NOMINA
   (CO_PROCESO_NOM, CO_PARAMETRO_NOM, VA_PARAMETRO_NOM, TX_PARAMETRO_NOM)
 Values
   ('ENCU', '26', 476.8, 'SIMVASTATINA 40 MG X 10 TABLETAS');
Insert into PERSONAL.PARAMETRO_NOMINA
   (CO_PROCESO_NOM, CO_PARAMETRO_NOM, VA_PARAMETRO_NOM, TX_PARAMETRO_NOM)
 Values
   ('ENCU', '27', 450, 'TADALAFIL 20 MG X 2 TABLETAS REC.');
Insert into PERSONAL.PARAMETRO_NOMINA
   (CO_PROCESO_NOM, CO_PARAMETRO_NOM, VA_PARAMETRO_NOM, TX_PARAMETRO_NOM)
 Values
   ('ENCU', '28', 2500, 'VIAJESAN 50 MG X 10 TAB');
COMMIT;
